/*
 * __GAME__.java
 *
 * An autogenerated file for your game
 */
package __NAMESPACE__;

import org.libsdl.app.*;
import android.os.Bundle;
import androidx.core.splashscreen.*;

/**
 * The Java entrypoint for a CUGL game
 *
 * The class name is customized to match the settings of your game
 */
public class __GAME__ extends APPActivity {

    /**
     * Initializes the application with the SDL Theme
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        // Handle the splash screen transition.
        SplashScreen splashScreen = SplashScreen.installSplashScreen(this);
        super.onCreate(savedInstanceState);
    }

}
